version: '3.8'

services:
  web:
    build: .
    container_name: apache_tp3
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mariadb_tp3
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/initdb:/docker-entrypoint-initdb.d
